config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :stations, dependent: :destroy
  accepts_nested_attributes_for :stations, allow_destroy: true, reject_if: :all_blank
  # validates :name,price,addres,age,content, presence: true
  validates :name,presence: true
  validates :price,presence: true
  validates :addres,presence: true
  validates :old,presence: true
  validates :content,presence: true
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    # @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
    @room.stations.build
    1.times { @room.stations.build }
  end

  # GET /rooms/1/edit
  def edit
    1.times { @room.stations.build }
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :price, :addres, :old, :content, stations_attributes: [:id, :station_name, :route_name, :walking_time])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExamRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: @room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :物件名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :賃料 %>
    <%= form.text_field :price %>円
  </div>

  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :addres %>
  </div>

  <div class="field">
    <%= form.label :築年数 %>
    <%= form.text_field :old %>年
  </div>

  <div class="field">
    <%= form.label :備考 %>
    <%= form.text_area :content %>
  </div>
  <hr>
    <% n = 0 %>
    <%= form.fields_for :stations do | station | %>
      <h3>最寄駅<%= n += 1 %></h3>
      <div class="field">
        <%= station.label :路線名 %>
        <%= station.text_field :route_name %>
      </div>
      <div class="field">
        <%= station.label :駅名 %>
        <%= station.text_field :station_name %>
      </div>
      <div class="field">
        <%= station.label :徒歩分数 %>
        <%= station.text_field :walking_time %>分
      </div>      
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>物件編集</h1>

<%= render 'form', room: @room %>

<%= link_to '詳細', @room %> |
<%= link_to '戻る', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.price %></td>
        <td><%= room.addres %></td>
        <td><%= room.old %></td>
        <td><%= room.content %></td>
        <td><%= link_to '詳細', room %></td>
        <td><%= link_to '編集', edit_room_path(room) %></td>
        <td><%= link_to '削除', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_room_path %>

app/views/rooms/new.html.erb
<h1>物件登録</h1>

<%= render 'form', room: @room %>

<%= link_to '戻る', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>物件名:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>賃料:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>住所:</strong>
  <%= @room.addres %>
</p>

<p>
  <strong>築年数:</strong>
  <%= @room.old %>
</p>

<%# 最寄駅の数 %>
<%= form_with(model: @room, local: true) do |form| %>
  <% n = 0 %>
  <%= form.fields_for :stations do | station | %>
  <% n += 1 %>
  <% end %>
  <h4>最寄駅の数:<%= n %></h4>
<% end %>

<p>
  <strong>備考:</strong>
  <%= @room.content %>
</p>
<hr>
<%= link_to '編集', edit_room_path(@room) %> |
<%= link_to '戻る', rooms_path %>